sudo: required
dist: trusty
language: python
cache: pip
services:
  - docker
  - redis
python:
    - "3.5"
env:
  global:
     - OK_ENV=test
     - secure: "Lt5WB2HNpohoX2bgTytQTdBq3aYjn+GfW8YfjwMreKZ+TJKkprPBE4ODkKKF95wucji+2Vz3mztm5wnyk/WCkq1u1T/nY2YIiDrIWRkDQmEuyYb/mOdj00LZ50ax9us1USbFRTwd26AogDFM4YK32g5gQbO+bsbmzn1vcUVsgQY="
     - secure: "ELMophdX/+F2i10nRo7d0kiubvT952FxnrxCMvZtBovHRZCOHC/HMgGNcYkspVZMbOKea5jluA4M3bQUP1XjmB3B8SbWHmWsy6q6KfHoicA9FJjUyxfqHpHOCwYPZ4OKNAYjQB1tLFSau2mmydGCpdQoRxq+k3KdyIr9CITQFUQ="
     - secure: "Lh9Cqa6Gt5IEU+R+e1Z+SswOO7RyYNshxF/1x7nINyO9GGQ4yDd764+Nrd27MuXP7cY3t8/kQ+ox5uq9ODxSjXRlWxw8zQ8nAa0BJkayqOa8Nbvv2HSpyIHMTDAqahmCerTEdH8QT+i3x1hqxsbOBdxAVzOs4mFaZJsbuonF+w4="
  matrix:
    - USE_DOCKER=1
    - USE_NATIVE=1
install:
  - if [ -n "$USE_DOCKER" ]; then travis_retry make docker-build; fi
  - if [ -n "$USE_NATIVE" ]; then travis_retry pip --timeout=60 install -r requirements.txt; fi
  - if [ -n "$USE_NATIVE" ]; then travis_retry pip --timeout=60 install pytest-timeout python-coveralls; fi
script:
  - if [ -n "$USE_DOCKER" ]; then make docker-test; fi
  - if [ -n "$USE_NATIVE" ]; then py.test --cov-report term-missing --cov=server tests/  --ignore tests/test_web.py --timeout=30; fi
after_success:
  - if [ -n "$USE_NATIVE" ]; then echo "eventually should run coveralls here"; fi
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: mGqCgRCFMB89AKsYVOZI79sifCFOLaQkuY3rvFKMitpD1GYQQpkBbZ9Z1SWi0VQV63oOKTQBrPCeDSwhZMaJA/dCZZIuz6e9nkVyJJUIrqAuH9PjgQr6FM4FkKzVLpHdPnXIikAvUAKiPRzzj8z4KO1EohBRR/xb2/4TpoWrkSA=
