sudo: required
dist: trusty
language: python
cache: pip
services:
  - docker
  - redis
python:
    - "3.5"
env:
  global:
     - OK_ENV=test
     - secure: "Y2SL/twBTKPRR1ur7+0yZxuzZy16a9iqP0Y/vtrZ8H45r9Mlj/jnxDq/am4Yd6PzZsKax4wSnZBjzl/uC7nqS0c0vuZtHbq1fVSKVjui4G7MJf+23qjOg8X36ZIornvFl3CGGpAYrbZchhV55nHKChhE46VZM8Vo8w9Gm7wBriQ="
     - secure: "AuOauqN0JtMArDf7Mcjd4IyuKip7hODQaLWssRdb2LvRUTOlA7AQiIH8PYPwesseHdVahbcnnLvCQm7vPnBNmLcOeDzRfJxZeLyBaB1oNnTCqVCEhlUEPAUDbVNE/gIF27Goq3VY5inDwz+v5zLfGqQGAsqMEZm+FPtQA73Vl0Q="
     - secure: "b3SRwhqbVl/8eKcqZtR07ko7HIjrg9sOhCjhGThWRCSG0OYL8ilsorWJsUxlvlkxuKi/7nVDh7gWZHlEhxmiSH+8dxVX6GSUr/7mUU7cnjynPqRQft97xxdfbeG7tGAv03Z6Mu7QIkUakkKgp/TnOovG7msDXIuiXm3yYbea3lc="
  matrix:
    - USE_DOCKER=1
    - USE_NATIVE=1
install:
  - if [ -n "$USE_DOCKER" ]; then travis_retry make docker-build; fi
  - if [ -n "$USE_NATIVE" ]; then travis_retry pip --timeout=60 install -r requirements.txt; fi
  - if [ -n "$USE_NATIVE" ]; then travis_retry pip --timeout=60 install pytest-timeout python-coveralls; fi
script:
  - if [ -n "$USE_DOCKER" ]; then make docker-test; fi
  - if [ -n "$USE_NATIVE" ]; then py.test --cov-report term-missing --cov=server tests/  --ignore tests/test_web.py --timeout=30; fi
after_success:
  - if [ -n "$USE_NATIVE" ]; then echo "eventually should run coveralls here"; fi
notifications:
  email: false
  slack:
    on_success: never
    on_failure: always
    secure: mGqCgRCFMB89AKsYVOZI79sifCFOLaQkuY3rvFKMitpD1GYQQpkBbZ9Z1SWi0VQV63oOKTQBrPCeDSwhZMaJA/dCZZIuz6e9nkVyJJUIrqAuH9PjgQr6FM4FkKzVLpHdPnXIikAvUAKiPRzzj8z4KO1EohBRR/xb2/4TpoWrkSA=
